version: '3'
services:
  ros-core:
    image: ros:melodic
    command: roscore
    restart: always
    network_mode: host

  ros-mavros:
    build: ros-mavros
    image: frobit-mavros:latest
    command: roslaunch --wait mavros px4.launch
    depends_on:
      - ros-core
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /dev/:/dev/

  ros-px4-adapter:
    image: frobit-mavros:latest
    command: python /scripts/px4_adapter_node.py
    depends_on:
      - ros-core
    restart: always
    network_mode: host
    volumes:
      - ./ros-px4-adapter/scripts/:/scripts/

  ros-pid:
    build: ros-pid
    command: roslaunch --wait /scripts/frobit.launch
    depends_on:
      - ros-core
    restart: always
    network_mode: host
    volumes:
      - ./ros-pid/scripts/:/scripts/

  ros-frobit-driver:
    build: ros-frobit-driver
    command: stdbuf -o L python /scripts/frobit_node.py
    depends_on:
      - ros-core
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./ros-frobit-driver/scripts/:/scripts/
      - /sys/class/:/sys/class/
