version: '3'
services:
  ros-core:
    image: ros:melodic
    command: roscore
    restart: always
    network_mode: host

  ros-pid:
    build: ../ros-pid/
    restart: always
    network_mode: host
    command: roslaunch --wait /scripts/frobit.launch
  
  ros-frobit-driver:
    build: ../ros-frobit-driver/
    restart: always
    network_mode: host
    privileged: true
    command: stdbuf -o L python /scripts/frobit_node.py
    volumes:
     - /home/pi/src/ros-frobit-driver/scripts/:/scripts/
     - /sys/class/:/sys/class/
