version: '3'
services:
#  ros-core:
#    image: ros:melodic
#    command: roscore
#    restart: always
#    network_mode: host

  mavros:
    build: ../ros-mavros/
    command: roslaunch mavros px4.launch
    restart: always
    network_mode: host
    privileged: true
    volumes:
    - /dev/:/dev/

  ros-px4-adapter:
    image: ros:melodic
    command: python /scripts/px4_adapter_node.py
    restart: always
    network_mode: host
    volumes:
    - /home/pi/src/ros-px4-adapter/scripts/:/scripts/

  ros-pid:
    build: ../ros-pid/
    command: roslaunch --wait /scripts/frobit.launch
    restart: always
    network_mode: host
    volumes:
    - /home/pi/src/ros-pid/scripts/:/scripts/
  
  ros-frobit-driver:
    build: ../ros-frobit-driver/
    command: stdbuf -o L python /scripts/frobit_node.py
    restart: always
    network_mode: host
    privileged: true
    volumes:
    - /home/pi/src/ros-frobit-driver/scripts/:/scripts/
    - /sys/class/:/sys/class/
